export enum ActionTypes {
  RESET_JOB_HISTORY = 'RESET_JOB_HISTORY',
  TOGGLE_ITEM_VISIBILITY_FAVORITE = 'TOGGLE_ITEM_VISIBILITY_FAVORITE',
  TOGGLE_ITEM_VISIBILITY_EXPANDED = 'TOGGLE_ITEM_VISIBILITY_EXPANDED',
  TOGGLE_ITEM_VISIBILITY_CONDENSED = 'TOGGLE_ITEM_VISIBILITY_CONDENSED'
}
