export enum MutationTypes {
  SET_JOB_HISTORY = 'SET_JOB_HISTORY',
  TOGGLE_ITEM_VISIBILITY_FAVORITE = 'TOGGLE_ITEM_VISIBILITY_FAVORITE',
  TOGGLE_ITEM_VISIBILITY_EXPANDED = 'TOGGLE_ITEM_VISIBILITY_EXPANDED',
  TOGGLE_ITEM_VISIBILITY_CONDENSED = 'TOGGLE_ITEM_VISIBILITY_CONDENSED',
  TOGGLE_ITEM_VISIBILITY_HIDDEN = 'TOGGLE_ITEM_VISIBILITY_HIDDEN',

  TOGGLE_ITEMS_EXPAND_BY_TAG = 'TOGGLE_ITEMS_EXPAND_BY_TAG',
  TOGGLE_ITEMS_COLLAPSE_ALL = 'TOGGLE_ITEMS_COLLAPSE_ALL',
  TOGGLE_ITEMS_EXPAND_ALL = 'TOGGLE_ITEMS_EXPAND_ALL',

  SET_INDEX_CONDENSED = 'SET_INDEX_CONDENSED',
}
